CREATE TABLE IF NOT EXISTS "CUSTOMER" (
	"CID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"NAME"	TEXT NOT NULL,
	"MOB"	TEXT,
	"ADD"	TEXT
);

CREATE TABLE IF NOT EXISTS  "CATEGORIES" (
	"CATEID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"CATENAME"	TEXT NOT NULL UNIQUE
)

CREATE TABLE IF NOT EXISTS  "INVENTORY_TAGS" (
	"TAGID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"TAGNAME"	INTEGER NOT NULL UNIQUE
)

CREATE TABLE IF NOT EXISTS "DEALERS" (
	"DID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"NAME"	TEXT NOT NULL,
	"MOB"	TEXT
)

CREATE TABLE IF NOT EXISTS  "INVENTORY" (
	"INVID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"IMAGE"	TEXT,
	"DP"	INTEGER,
	"MARGIN"	INTEGER,
	"DID"	INTEGER NOT NULL,
	"INVTYPE"	INTEGER NOT NULL,
	"ITEMDESC"	TEXT , 
    FOREIGN KEY(DID) REFERENCES DEALERS(DID),
	FOREIGN KEY (INVTYPE) REFERENCES CATEGORIES(CATEID)
)

CREATE TABLE  IF NOT EXISTS "DEALER_CATEGORY_MAP" (
	"DID"	INTEGER NOT NULL,
	"CATEID"	INTEGER NOT NULL,
	FOREIGN KEY(DID) REFERENCES DEALERS(DID),
	FOREIGN KEY (CATEID) REFERENCES CATEGORIES(CATEID)
)

CREATE TABLE  IF NOT EXISTS "INVENETORY_TAG_MAP" (
	"INVID"	INTEGER NOT NULL,
	"TAGID"	INTEGER NOT NULL,
	FOREIGN KEY(INVID) REFERENCES INVENTORY(INVID),
	FOREIGN KEY (TAGID) REFERENCES INVENTORY_TAGS(TAGID)
)

CREATE TABLE IF NOT EXISTS "CUSTOMER_ORDERS" (
	"OID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"CID"	INTEGER NOT NULL,
	"INVID" INTEGER NOT NULL ,
	"BTIME"	TEXT NOT NULL,
	"BDATE"	TEXT NOT NULL,
	"ESTDEVDATE"	TEXT,
	"PP"	INTEGER NOT NULL,
	"ISBOOKED"	INTEGER,
	"ISDELIVERED"	INTEGER,
	"ISPAID"	INTEGER,
	FOREIGN KEY(CID) REFERENCES CUSTOMER(CID),
	FOREIGN KEY (INVID) REFERENCES INVENTORY(INVID)	
)